Added theming
Petelliott/chat pull request #19
Opened 2017-09-18 00:23 UTC by jacobrec

2017-09-18 02:03 UTC, Petelliott commented
ill merge this if you fix the problem where the hover highlighting is always on.

2017-09-18 02:43 UTC, petelliott requested changes
this will not be merged until messages are not constanly hover hilighted

2017-09-19 16:15 UTC, jacobrec commented
messages are not constantly hover highlighted, it's a different colour and its so you can quickly see which messages are yours

2017-09-19 17:07 UTC, petelliott approved these changes

2017-09-19 17:07 UTC, merged